name: master

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        id: node
      - run: npm ci
      - run: npm audit fix
      - run: npm install typescript --global
      - run: tsc

  publish-npm:
    needs: ['build-unix']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm install typescript --global
      - run: tsc
      - run: git config --global user.email "mikaelvesavuori@gmail.com"
      - run: git config --global user.name "Mikael Vesavuori"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
